# Generated by Django 5.1.5 on 2025-02-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_ingredient_quantity_alter_recipe_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
