# Generated by Django 5.1.5 on 2025-02-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_remove_ingredient_quantity_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipeapp.ingredient'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
