# Generated by Django 5.1.5 on 2025-02-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_remove_ingredient_quantity_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
